apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: rdsmonitors.middleware.io
spec:
  group: middleware.io
  names:
    kind: RdsMonitor
    listKind: RdsMonitorList
    plural: rdsmonitors
    singular: rdsmonitor
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: RdsMonitor is the Schema for the rdsmonitors API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: RdsMonitorSpec defines the desired state of RdsMonitor
          properties:
            rdsAliyunAccount:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              items:
                properties:
                  accessKeyId:
                    type: string
                  accessKeySecret:
                    type: string
                  name:
                    type: string
                  regionId:
                    type: string
                required:
                - accessKeyId
                - accessKeySecret
                - name
                - regionId
                type: object
              type: array
          required:
          - rdsAliyunAccount
          type: object
        status:
          description: RdsMonitorStatus defines the observed state of RdsMonitor
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
