apiVersion: apps/v1
kind: Deployment
metadata:
  name: aliyun-monitor-operator
  namespace: ops-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      name: aliyun-monitor-operator
  template:
    metadata:
      labels:
        name: aliyun-monitor-operator
    spec:
      serviceAccountName: aliyun-monitor-operator
      containers:
        - name: aliyun-monitor-operator
          # Replace this with the built image name
          image: riet/aliyun-monitor-operator
          command:
          - aliyun-monitor-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "aliyun-monitor-operator"
