kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: aliyun-monitor-operator
  namespace: ops-monitor
subjects:
- kind: ServiceAccount
  name: aliyun-monitor-operator
  namespace: ops-monitor
roleRef:
  kind: Role
  name: aliyun-monitor-operator
  apiGroup: rbac.authorization.k8s.io
